name: CI
run-name: CI ${{ github.event.head_commit.message || github.event.pull_request.title }}

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  ci:
    uses: bamiyanapp/dev-standards/.github/workflows/reusable-ci.yml@main
    with:
      frontend_dir: frontend
      backend_dir: backend
      base_branch: main
      enable_release: true
      enable_changelog_json: true
      changelog_json_output_path: frontend/src/changelog.json
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
